"""D1-2 integration: the fully self-contained node chain.

camera flash (time-zero) -> anchored thunder onset -> implied range ->
cross-node consistency selection -> trilateration. No satellite anchor, no
cross-node clock sync — each node self-clocks its own flash-to-bang delay
(plan F1). Candidate ranges from multiple nodes are reconciled by joint
consistency (one candidate per node, lowest joint rms — the M5 fusion rule).

Needs the demo storm on disk (generated by the dashboard's demo mode).
Run:  python detectors/tests/test_integration.py
"""
import datetime
import itertools
import json
import pathlib
import sys

import soundfile as sf

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "dashboard"))

from detectors import anchors, flash, thunder  # noqa: E402
from fp import geo  # noqa: E402

MAN = ROOT / "data" / "demo" / "manifest.json"
TARGET_STRIKE = 1  # S2
MAX_ERR_M = 400


def epoch(s):
    return datetime.datetime.fromisoformat(s).timestamp()


def main():
    if not MAN.exists():
        print("SKIP: demo storm not generated (run the dashboard demo once)")
        return
    man = json.loads(MAN.read_text())
    truth = [(epoch(s["time"]), s["lat"], s["lon"], s["id"]) for s in man["strikes"]]
    temp = man["temp_c"]
    lat0, lon0 = man["center"]["lat"], man["center"]["lon"]
    ts, slat, slon, sid = truth[TARGET_STRIKE]

    node_candidates = []
    for node in man["nodes"][:4]:
        vsn = node["vsn"]
        frames = sorted((epoch(m["timestamp"]), m["path"]) for m in man["media"]
                        if m["vsn"] == vsn and m["task"] == "storm-cam")
        ev = flash.detect_flashes([t for t, _ in frames],
                                  [flash.frame_luma(p) for _, p in frames])
        cam_anchors = flash.anchor_epochs(ev)  # time-only anchors, no ranges
        clips = sorted((epoch(m["timestamp"]), m["path"]) for m in man["media"]
                       if m["vsn"] == vsn and m["task"] == "storm-audio")
        t_clip, p_clip = min(clips, key=lambda c: abs(c[0] - (ts - 5)))
        y, sr = sf.read(p_clip, dtype="float32")
        if y.ndim > 1:
            y = y.mean(axis=1)
        rel = anchors.clip_relative(cam_anchors, t_clip, len(y) / sr,
                                    thunder.Config(temp_c=temp))
        evs = thunder.detect(y, sr, anchor_times_s=rel,
                             cfg=thunder.Config(temp_c=temp), wind_ms=3.0)
        cands = [e.implied_range_km * 1000 for e in evs if e.passed and e.anchored]
        d_true = geo.dist_km(node["lat"], node["lon"], slat, slon)
        print(f"  {vsn}: candidate range(s) {[round(c / 1000, 2) for c in cands]} km "
              f"(true {d_true:.2f})")
        if cands:
            node_candidates.append(
                (geo.to_xy(node["lat"], node["lon"], lat0, lon0), cands))

    assert len(node_candidates) >= 3, "need >=3 nodes with candidates"
    best = None
    for combo in itertools.product(*[c for _, c in node_candidates]):
        est = geo.trilaterate([xy for xy, _ in node_candidates], list(combo),
                              [200.0] * len(combo))
        if est and (best is None or est["rms_m"] < best[0]["rms_m"]):
            best = (est, combo)
    est, combo = best
    ela, elo = geo.to_latlon(*est["xy"], lat0, lon0)
    err = geo.dist_km(ela, elo, slat, slon) * 1000
    print(f"SELF-CONTAINED FIX ({sid}): {len(combo)} camera+mic nodes -> "
          f"strike err {err:.0f} m (rms {est['rms_m']:.0f} m, "
          f"gdop {est['gdop']:.1f}; no satellite, no clock sync)")
    assert err < MAX_ERR_M, f"strike error {err:.0f} m exceeds {MAX_ERR_M} m"
    print("INTEGRATION PASS")


if __name__ == "__main__":
    main()
